### ISSUE TITLE
Updating translations extremely slow

### ISSUE THREAD

**Issue by janholas** [directus/api#1409]
# Bug Report

Hi, I am having some trouble with the response times saving translation interface.
I have a collection with translation interface (13 translations) each with cca 15 fields and updating the collection takes really long time. I was able to locate the major slowdown in the call `$relationalCollectionData = $this->findByIds(...)` in two nested foreach loops in `validateAliasCollection(...)` function in `ItemsService.php`.  I didn't get much further from here, is there some way to optimize this? I also noticed that the APP sends to update array of all the translations and all their fields even though they didn't update (only one field in one translation updated for example)

## Steps to Reproduce

I am attaching whole directus DB dump of a MWE setup, login is: admin@admin.com / directus
DB dump to download: http://bit.ly/2Cynbes

Login, go to Country collection, select Portugal, update one translated field (any) and press save. 

## Expected Behavior

Collection to be saved in reasonable time

## Actual Behavior

Saving takes over a minute (can timeout on webserver if not configured for longer timeout)

## Other Context & Screenshots

DB Dump to download: http://bit.ly/2Cynbes

## Technical Details

- APP Version: 7.11.0
- API Version: 2.6.0
- Device: Desktop
- OS: Windows 10.1803
- Web Server: nginx 1.17.5
- PHP Version: 7.3.10
- Database: MySQL 5.7.22
- Install Method: docker

**Comment by nachogarcia** [comment]
How did you configure the webserver to avoid timeout @blackfox00 ?
I'm trying adding this to my k8s, but the error only changed to the following screenshot:
```
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "php-ini-add 'upload_max_filesize=20M' && php-ini-add 'post_max_size=20M' && php-ini-add 'max_execution_time=360'"]
```
![image](https://user-images.githubusercontent.com/9975630/71645158-41fcd900-2cd4-11ea-9771-eb26e960eeb6.png)
This is a big issue for us, at the beginning we didn't have any errors but now almost every collection suffers from it and we cannot use the app.

Any suggested workarounds @rijkvanzanten ?
