### ISSUE TITLE
Login won't work after setting a project logo, when using Redis cache

### ISSUE THREAD

**Issue by ale-rinaldi** [directus/api#1701]
On a fresh setup of Directus 8.4.0, with Redis as cache backend, the login to the app fails after setting a project logo.

**Steps to reproduce**
- Create this docker-compose file
```yaml
---
version: "3"

services:
  redis:
    image: redis

  db:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: directus
      MYSQL_USER: directus
      MYSQL_PASSWORD: directus
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  directus:
    image: directus/directus:v8-apache
    ports:
      - "8080:80"
    environment:
      DIRECTUS_AUTH_PUBLICKEY:      "123456"
      DIRECTUS_AUTH_SECRETKEY:      "654321"
      DIRECTUS_CACHE_ENABLED:       "true"
      DIRECTUS_CACHE_POOL_ADAPTER:  redis
      DIRECTUS_CACHE_POOL_HOST:     redis
      DIRECTUS_CACHE_POOL_PORT:     "6379"
      DIRECTUS_DATABASE_HOST:       db
      DIRECTUS_DATABASE_NAME:       directus
      DIRECTUS_DATABASE_USERNAME:   directus
      DIRECTUS_DATABASE_PASSWORD:   directus
      DIRECTUS_INSTALL_EMAIL:       test@test.it     
      DIRECTUS_INSTALL_PASSWORD:    supersecret
    links:
      - db:db
```
- Start the project:
```sh
docker-compose up -d
```
- Install Directus:
```sh
docker-compose run directus install
```
- Navigate to http://localhost:8080 and login with user _test@test.it_ and password _supersecret_ (the login will succeed)
- Go to _Settings_ -> _Global settings_ and upload an image as _Project logo_. Save the settings.
- Log out and try to log in again. The login will fail with a generic `Couldn't Reach API`.

At this point, if I flush the Redis cache with `docker-compose exec redis redis-cli flushall` the login will work for one time. Then, if I log out and in again, it won't work until I flush the cache again.

This doesn't happen if I disable the cache.
