### ISSUE TITLE
Performace - Response times

### ISSUE THREAD

**Issue by cupcakearmy** [directus/api#1743]
## Issue

So the issue is that the api takes really long time to respond to even the simplest requests.
I can range from ~150ms in the best cases to even almost a whole second. Basically this makes directus impossible to use in server side rendering. Is there any way to speed up calls? I have not found anything about it in the docs.

## Pics
<img width="960" alt="Screenshot 2020-02-07 at 16 16 28" src="https://user-images.githubusercontent.com/14948823/74041823-ad6a5280-49c6-11ea-9dd1-23a22600aa4c.png">

<img width="958" alt="Screenshot 2020-02-07 at 16 16 48" src="https://user-images.githubusercontent.com/14948823/74041858-bb1fd800-49c6-11ea-8bf5-137f88b03037.png">

## Versions

Pulled the latest image before creating the issue

- directus/directus:v8-apache
- mysql:5.7
- Apache/2.4.38 (Debian) PHP/7.3.14

**Comment by nachogarcia** [comment]
Do you have cache enabled?

Also, we're caching everything in top of it with cloudflare.

**Comment by cupcakearmy** [comment]
I've enabled it, not it takes "only" ~130ms. There is not way to get that faster I guess then.

For reference:

###### docker-compose.yml

```yaml
version: '3.7'

services:
  mysql:
    image: mysql:5.7
    env_file: .env
    volumes:
      - ./data/db:/var/lib/mysql

  directus:
    image: directus/directus:v8-apache
    env_file: .env
    ports:
      - 80:80
    volumes:
      - ./data/config:/var/directus/config
      - ./data/uploads:/var/directus/public/uploads
```

###### .env

```
MYSQL_DATABASE=directus
MYSQL_USER=directus
MYSQL_PASSWORD=xxx
MYSQL_RANDOM_ROOT_PASSWORD=yes

DIRECTUS_ENV=production
DIRECTUS_CACHE_ENABLED=true
DIRECTUS_CACHE_RESPONSETTL=3600
DIRECTUS_AUTH_PUBLICKEY=xxx
DIRECTUS_AUTH_SECRETKEY=xxx
DIRECTUS_DATABASE_HOST=mysql
DIRECTUS_DATABASE_PORT=3306
DIRECTUS_DATABASE_NAME=directus
DIRECTUS_DATABASE_USERNAME=directus
DIRECTUS_DATABASE_PASSWORD=xxx
```
